### ISSUE TITLE
Namespacing-dependencies

### ISSUE THREAD

**Issue by SonglinYu1230** [aranasaurus/space-playground#14]
Hi, I can't find your email. So I create a new issue here to ask a question about namespacing dependencies. 
dx.esri.com/blog/2013/12/13/namespacing-dependencies,  the article is disappear.
Do you have a copy of the article ? 
Can you send me a copy ?  my email is webmanyu@gmail.com. Thank you very much.

**Comment by aranasaurus** [comment]
Sorry, I don't have a copy of that article :( It's far out of date these days anyway. Also, my apologies for not seeing this until now as well!
